services:
  app:
    container_name: "app"
    restart: always
    build: 
      context: ./app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app/app
      - /app/node_modules
      - ./database:/app/database
    command: sh -c "npx sequelize-cli db:migrate && npm start"   